package dock

import (
	"github.com/pkg/errors"
	log "github.com/sirupsen/logrus"
	"github.com/plantoncloud/mactl/internal/lib/plist"
	"github.com/plantoncloud/mactl/internal/lib/shell"
	"os/exec"
)

const (
	PlistB64   = "YnBsaXN0MDDfEBABAgMEBQYHCAkKCwwNDg8QERITFBUXNTY3ODkTOzE8PVxzaG93LXJlY2VudHNfEBdsYXN0LW1lc3NhZ2V0cmFjZS1zdGFtcFhhdXRvaGlkZVd2ZXJzaW9uXxAUbGFzdC1hbmFseXRpY3Mtc3RhbXBfEBFwZXJzaXN0ZW50LW90aGVyc1h0aWxlc2l6ZV8QD3BlcnNpc3RlbnQtYXBwc1ltb2QtY291bnRWcmVnaW9uWWxhcmdlc2l6ZVp0cmFzaC1mdWxsW3JlY2VudC1hcHBzXxARd3ZvdXMtYnItbW9kaWZpZXJTbG9jXxAPd3ZvdXMtYnItY29ybmVyCCNBwzL1bWbOaAkQAaEWI0HDpd7/2GgroRjTGRobHB0eVEdVSURZdGlsZS10eXBlWXRpbGUtZGF0YRIhgoxtXmRpcmVjdG9yeS10aWxl2h8gISIjJCUmJygUKSorLDEyMyk0VnNob3dhc1lmaWxlLXR5cGVfEA9wYXJlbnQtbW9kLWRhdGVUYm9va1lmaWxlLWRhdGFZZGlzcGxheWFzWmZpbGUtbGFiZWxdZmlsZS1tb2QtZGF0ZVthcnJhbmdlbWVudF8QEXByZWZlcnJlZGl0ZW1zaXplEAITAAAJMtw/pYxPEQKQYm9va5ACAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjAEAAAQAAAADAwAAAAAAIAUAAAABAQAAVXNlcnMAAAAHAAAAAQEAAHN3YXJ1cGQACQAAAAEBAABEb3dubG9hZHMAAAAMAAAAAQYAABAAAAAgAAAAMAAAAAgAAAAEAwAAXFMAAAAAAAAIAAAABAMAAF2iCAAAAAAACAAAAAQDAACQoggAAAAAAAwAAAABBgAAWAAAAGgAAAB4AAAACAAAAAAEAABBwVOc/AAAABgAAAABAgAAAgAAAAAAAAAPAAAAAAAAAAAAAAAAAAAACAAAAAQDAAABAAAAAAAAAAQAAAADAwAA9gEAAAgAAAABCQAAZmlsZTovLy8MAAAAAQEAAE1hY2ludG9zaCBIRAgAAAAEAwAAAKAgaHQAAAAIAAAAAAQAAEHCjNCu2MD5JAAAAAEBAABDNEJGRUQ5MS04QjkyLTQzMjItOEE2OS00OURFNjI1OURDNTEYAAAAAQIAAIEAAAABAAAA7xMAAAEAAAAAAAAAAAAAAAEAAAABAQAALwAAAAAAAAABBQAAzAAAAP7///8BAAAAAAAAABAAAAAEEAAARAAAAAAAAAAFEAAAiAAAAAAAAAAQEAAArAAAAAAAAABAEAAAnAAAAAAAAAACIAAAeAEAAAAAAAAFIAAA6AAAAAAAAAAQIAAA+AAAAAAAAAARIAAALAEAAAAAAAASIAAADAEAAAAAAAATIAAAHAEAAAAAAAAgIAAAWAEAAAAAAAAwIAAAhAEAAAAAAAABwAAAzAAAAAAAAAARwAAAIAAAAAAAAAASwAAA3AAAAAAAAAAQ0AAABAAAAAAAAADSLS4vMF8QEF9DRlVSTFN0cmluZ1R5cGVcX0NGVVJMU3RyaW5nEA9fECBmaWxlOi8vL1VzZXJzL3N3YXJ1cGQvRG93bmxvYWRzLxAAWURvd25sb2FkcxMAAGsJ3D+kehP//////////yJCgAAAoBECWlJVUyJDAAAACaBYZW5fVVM6VVMQDQAIACsAOABSAFsAYwB6AI4AlwCpALMAugDEAM8A2wDvAPMBBQEGAQ8BEAESARQBHQEfASYBKwE1AT8BRAFTAWgBbwF5AYsBkAGaAaQBrwG9AckB3QHfAegEfASBBJQEoQSjBMYEyATSBNsE5ATpBOoE7QTwBPUE9gT3BQAAAAAAAAACAQAAAAAAAAA+AAAAAAAAAAAAAAAAAAAFAg=="
	AppGroupId = "com.apple.dock"
)

func Optimize() error {
	log.Infof("importing dock config from plist file")
	if err := plist.Import(AppGroupId, PlistB64); err != nil {
		return errors.Wrapf(err, "failed to import %s plist file", AppGroupId)
	}
	log.Infof("imported dock config from plist file")
	log.Infof("restarting dock")
	if err := restart(); err != nil {
		return errors.Wrap(err, "failed to restart")
	}
	log.Infof("restarted dock")
	return nil
}

func restart() error {
	if err := shell.RunCmd(exec.Command("killall", "Dock")); err != nil {
		return errors.Wrap(err, "failed to restart dock")
	}
	return nil
}
